import '../styles/style.scss'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import { CartProvider } from '@/context/CartContext'
import CartSidebar from '@/components/CartSidebar'
import { UserProvider } from '@/context/UserContext'
import { FoodItemsProvider } from '@/context/FoodItemContext'
import { LoadingProvider } from '@/context/LoadingContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {





  return (
    <html lang="en">
      <LoadingProvider>
       <FoodItemsProvider>
      <UserProvider>
      <CartProvider>
      <body className={inter.className}>
        <Navbar/>
        {children}
    
        </body>
        </CartProvider>
        </UserProvider>
        </FoodItemsProvider>
        </LoadingProvider>
    </html>
  )
}
